# Generated by Django 3.2.23 on 2023-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='genre',
        ),
    ]
