# Generated by Django 3.2.23 on 2023-12-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20231205_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=' ', editable=False, max_digits=6),
        ),
    ]
