# Generated by Django 3.2.23 on 2023-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_orderdetail_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='overall_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
