# Generated by Django 5.0 on 2023-12-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='countries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
