# Generated by Django 5.0 on 2023-12-10 11:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
