# Generated by Django 5.0 on 2023-12-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_order_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='countries',
            new_name='country',
        ),
    ]
