# Generated by Django 5.0 on 2023-12-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_rename_countries_order_country'),
        ('product', '0003_category_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='product.product'),
        ),
    ]
