# Generated by Django 3.2.23 on 2023-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
